### ISSUE TITLE
Stops at completion 

### ISSUE THREAD

**Issue by WowOkay** [Nexus-Mods/Nexus-Mod-Manager#102]
I'm trying to download the Family Legacy mod to Skyrim, but when I click the download button, it loads to twenty-seven megabytes (that's how big the mod is) and then it stops and the mod remains uninstalled. 

How do I fix this?

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
