### ISSUE TITLE
NMM Crash the game

### ISSUE THREAD

**Issue by WertCrafter** [Nexus-Mods/Nexus-Mod-Manager#104]
Ger= Alle meine spiele die ich mit NMM spiele stürzen zur zeit ab ( Skyrim Fallout 4)
bitte um Hilfe .

En= All of my games I play with NMM are currently playing (Skyrim Fallout 4)
Please help .

**Comment by squid-box** [comment]
Hallo! 

We'll need more info to help you. If this is a case of the games crashing due to mods you've added, you'll probably get more help from the Nexus Forums. 

If this is NMM itself crashing we can help, but you'll need to explain what you're doing when it crashes, and give us the trace log from the crash.
