### ISSUE TITLE
NMM will not create the Backup file

### ISSUE THREAD

**Issue by HLCaerdic** [Nexus-Mods/Nexus-Mod-Manager#1052]
NMM will not create the Mod Installation Backup File.. it gets to the point where it is creating the Zip file and fails.... 
[TraceLog20200907182137.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/5185490/TraceLog20200907182137.txt)

**Comment by BlazeStryker** [comment]
I wouldn't know about it starting as mine talks about there not being rtoom in C: drive. This is true, but I was trying to make the backup in the multiple-terabyte L: drive so WTF?

**Comment by squid-box** [comment]
@HLCaerdic : The issue is `There is not enough space on the disk. (0x80070070: DISK_FULL)`.
It could be related to #273, depending on your storage setup and state.

As it's been half a year since you reported this, I'm closing the issue - but please feel free to reopen it if you still have this issue and want help to resolve it.
