### ISSUE TITLE
Some  mods are not working on Fallout 4

### ISSUE THREAD

**Issue by LeoVB** [Nexus-Mods/Nexus-Mod-Manager#1087]
I have about 20 mods installed on de NNM, I already made the changes on the files so that the mods can work, and some of them do, but the weapon packs and the ones that change textures, don't, eventhough they appear to be enabled on the NNM, so I dont really know what to do

**Comment by LeoVB** [comment]
oh and I forgot to mention that when I enable the weapon's texture, they don't appear, mthe hands of the character are holding and invicible weapon, so I'm kinda sad about that

**Comment by SlinkyThePerson** [comment]
Post your load order

**Comment by Llexod69** [comment]
what do you mean?

**Comment by LeoVB** [comment]
> Post your load order

What do you mean?

**Comment by SlinkyThePerson** [comment]
Like, open your mod manager, screenshot/copy your load order, and paste it into here or on imgur so we can take a look at it. It sounds like one of your mods is conflicting with your weapon retextures and that's causing your bug.

**Comment by SlinkyThePerson** [comment]
For example My mod order for New Vegas looks like this:
![image](https://user-images.githubusercontent.com/78572987/107082984-936e7600-67ba-11eb-9de0-ac32b0fe2e76.png)

**Comment by LeoVB** [comment]
> For example My mod order for New Vegas looks like this:
> ![image](https://user-images.githubusercontent.com/78572987/107082984-936e7600-67ba-11eb-9de0-ac32b0fe2e76.png)

oh I 
![load order](https://user-images.githubusercontent.com/66802519/107085292-e85fbb80-67bd-11eb-9ed5-67959536f621.png)
![load order 2](https://user-images.githubusercontent.com/66802519/107085301-ec8bd900-67bd-11eb-99cf-0ee8a495b3c3.png)

see, thank you, here you go

**Comment by SlinkyThePerson** [comment]
So everything that's red is missing a master file that it needs to run properly, if you click on it it should show you a list of masters and one should be red with the word "Missing" Next to it. Looks to me like you're missing "Outcasts and Remnants - Quest Mod Plus" for depravity, plus ALL the DLC's, which you will need for most weapon mods. I didn't check each one individually on nexus, but if you download all the DLC's and then check your load order again there should be significantly less red. You should also look into downloading BLD patches for your weapon mods because they will be unbalanced without it. I wrote one for the service rifle you can [find here](https://www.nexusmods.com/fallout4/mods/48184), and the others will probably have some for theirs.

**Comment by LeoVB** [comment]
ok I see, so the problem is that I dont have de DLC's downloaded, but how do I download them? Cause they need to be paid for, right?

**Comment by SlinkyThePerson** [comment]
Yes, you can get them from wherever you bought fallout 4, probably steam, but if you did it through Bethesda you can get them there too. Alternatively you can uninstall al the mods that require the DLC's, from personal experience downloading more than 3 or 4 weapon mods isn't really necessary for a normal play-through because you'll end up picking a favorite and sticking with that one the whole game anyway.

**Comment by LeoVB** [comment]
Oh, ok, thank you for your help, I appreciate it
