### ISSUE TITLE
Stops working when starting a download during an installation

### ISSUE THREAD

**Issue by SieurArgon** [Nexus-Mods/Nexus-Mod-Manager#109]
Not that big of a deal, but since I tend to be pretty rush this is an issue I noticed :D I'd like to add that when clicking on a mod the "view" goes to the right so I can't see the name anymore and have to click on a category to go back to normal. Still really appreciate the app :D !

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
