### ISSUE TITLE
NMM totally freeze(still running and use CPU times but no response) when try to select a mod on the list.

### ISSUE THREAD

**Issue by playerlin** [Nexus-Mods/Nexus-Mod-Manager#1094]
**Describe the bug** 
NMM become totally freeze and no response when I try to install Updated Unofficial Fallout 3 Patch, well, NMM is freeze when I just click on that mod, I have to force shut down NMM, and cannot installed that mod as highlight it make NMM stopped responses.

**Environment**
- NMM version: 0.72.3
- Mod(s) used: Updated Unofficial Fallout 3 Patch : https://www.nexusmods.com/fallout3/mods/19122
No crash log or something since it just freeze/stop response.

**To Reproduce**
1. Go the Updated Unofficial Fallout 3 Patch modpage, download it via NMM.
2. After NMM downloaded and added it to the list, try to click it to install.
3. NMM just become busy and stop response, I tried wait few minutes still no response, until I force shut down. I restart NMM, it seems still fine until I click UUF3P line again = FREEZE.

EDIT : I found the package file(if I use Mod manager download link) named Updated Unofficial Fallout 3 Patch.fomod, changed the filename to Updated Unofficial Fallout 3 Patch.fomod.zip and NMM won't freeze anymore and I can install the mod like normally. I guess for some reasons my NMM didn't like that FOMOD file?

**Comment by playerlin** [comment]
I found the mod's package file is "Updated Unofficial Fallout 3 Patch.fomod". 
I just rename it to "Updated Unofficial Fallout 3 Patch.fomod.7z" and it seems working now and I can install the mod without problems.

**Comment by DuskDweller** [comment]
This issue was related to a bug into the built in web browser showing HTML mod description (the panel appearing on the right).
I fixed the endless freeze issue, but for this specific mod the amount of web links to parse is still big enough to cause a few seconds of freeze.
Keep in mind that the panel is still buggy and will be overhauled in a future release. (in fact for the time being I just don't use it, I click on the mod version to reach the Nexus page if I need mod info)

**Comment by DuskDweller** [comment]
Oh, and this should have been fixed in 0.80.1 .
