### ISSUE TITLE
Nexus Mod Manager will not open

### ISSUE THREAD

**Issue by erikabear1990** [Nexus-Mods/Nexus-Mod-Manager#11]
Nexus Mod Manager will not open after installing and I have tried finding user config but find nothing. I got nexus from their website (http://www.nexusmods.com/) but it wont work. I tried compatibility mode and tried running as admin. 
I have .NET 4.5 or 4.6 installed and have the newest java. 
I'm on windows 8.1, 64bit

**Comment by hjymnol** [comment]
I have this problem too ,before that I can use nexus normally.Now when I update to 0.63.6 ,I still use it normal like before and the next day it won't wan to launch.I open task manager ,I see it open and quickly disappear.
I have win 10

**Comment by DuskDweller** [comment]
Please be more specific describing what happens when try to launch it.

First thing you should try is:
- Right-click on the NMM installer program
- Click Properties
- Click Unblock
- Click OK
- Reinstall it.

**Comment by erikabear1990** [comment]
I am reinstalling windows 10 and trying that bc my friend said it may be bc I downgraded. If that doesn't work I'll let you guys know

**Comment by Assmandu** [comment]
Version 0.63.7 not launching.  No process running in task manager.  Using with SSE on Windows 10 64-bit.  Uninstalled 0.63.7 and installed 063.5.  Previous version of NMM launches normal.

**Comment by arthurh3535** [comment]
I can confirm the same issue. Windows 10 did not 'block' the install, but now it doesn't load at all. I think I saw something about UI authorization in task manager, but I couldn't get that to replicate.

One additional thing is that it was working, then quit after I had a power outage (old apartment and trying to keep warm  this winter).  Tried to reinstall, but that didn't seem to do anything at all.

A full uninstall (removing all configuration files) finally managed to get NMM to install. Now I just have to let it detect all my games again.

**Comment by squid-box** [comment]
@Assmandu: This sounds similar to another recent issue, if this is still a problem you could try:

> You could try going to %LOCALAPPDATA%\Black_Tree_Gaming\NexusClient.exe_<gibberish>\0.65.4.0 and renaming user.config to something else and see if that fixes the crash.
> 
> I'm not sure which settings are held there, but you might lose some settings in NMM (that's why I'd suggest renaming/moving the file, rather than deleting it).

If this is no longer a problem for you (2 years later), or if I don't hear from you in a while, I'll close this issue.

**Comment by Assmandu** [comment]
I dont have the issue anymore although I don’t recall how I resolved the issue.  I’m currently using the latest version of NMM...0.65.2.

On May 21, 2018, at 3:13 PM, Joel Ahlgren <notifications@github.com<mailto:notifications@github.com>> wrote:


@Assmandu<https://github.com/Assmandu>: This sounds similar to another recent issue, if this is still a problem you could try:

You could try going to %LOCALAPPDATA%\Black_Tree_Gaming\NexusClient.exe_\0.65.4.0 and renaming user.config to something else and see if that fixes the crash.

I'm not sure which settings are held there, but you might lose some settings in NMM (that's why I'd suggest renaming/moving the file, rather than deleting it).

If this is no longer a problem for you (2 years later), or if I don't hear from you in a while, I'll close this issue.

**Comment by squid-box** [comment]
Thank you, I'll close the issue :)
