### ISSUE TITLE
The mods I download Don't Show up In the Other NMM View in the Mods Tab

### ISSUE THREAD

**Issue by thethird2007** [Nexus-Mods/Nexus-Mod-Manager#118]
When I go click "Switch the Mod Manager views" I don't see my mods or anything.

**Comment by thethird2007** [comment]
They appear in my files, active mods, and plugins, but when I look at installed and total mods they both say 0!

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
