### ISSUE TITLE
Mod introuvable dans les plugins + code 740

### ISSUE THREAD

**Issue by Anjarxxx** [Nexus-Mods/Nexus-Mod-Manager#120]
(0.63.14)
Bonjour à tous, voici le problème que je viens d'avoir:
Lorsque je télécharge un mod depuis le Nexus, celui ci après l'activation dans l'onglet "MODS" n'est pas visible dans l'onglet "¨PLUGINS", je ne peux donc pas le coché.
J'ai donc désinstallé NMM et en réessayant de nouveau à télécharger un mod, le problème reste le même de plus, en réinstallant NMM, j'ai reçu un message d'erreur "nmm unable to execute file" "error 740". Je n'ai pas réussis à trouver une solution sur Internet, j’espère que vous pourrez m'aidez. Merci..

**Comment by squid-box** [comment]
18 months later: my french is non-existant, but from Google Translate I think the two problems are:
1. Error 740 : Is probably due to the installer being run without elevated priviliges - have you tried running the installer as administrator?
2. Are you still having problems with the mod not showing up under plugins? If so:
  a. Have you tried with the latest version of NMM?
  b. What game are you modding, and what mods are you having issues with? Could it be that it's a mod that doesn't have a plugin?
