### ISSUE TITLE
Latest versions have intermitent failure loading gif's from resources

### ISSUE THREAD

**Issue by deuspingu** [Nexus-Mods/Nexus-Mod-Manager#129]
System.Resources.ResourceManager.GetObject fails with AccessViolation exception - this happens for both the US flag and the loading_round indicator. 

Replacing these files with png versions and updated the resources file references fixes.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
