### ISSUE TITLE
Cant download mods

### ISSUE THREAD

**Issue by Fir3boy98** [Nexus-Mods/Nexus-Mod-Manager#132]
when i click nmm to download a mod nothing happens i think this may have something to do with me disabling teh open nmm whenever i click it but if so how do i undo that

**Comment by Fir3boy98** [comment]
when i click download with nmm a white box appears then disappears  and i had my NMM open while doing this and nothing appears in teh download manager

**Comment by Sulhir** [comment]
I have this exact problem with all mods for all games. I believe for me it is because I have both the games and NMM installed to a hard drive that does not have my Windows installation on it. Windows hardly knows my files are there (indexing and searches do not search this hard drive for whatever reason) and I believe this is why.
I can still download mods manually and add them via the "add mod from file/url" button. I'd like to be able to test the "add mod from URL" function but it is looking for some odd link format that I do not understand.

**Comment by squid-box** [comment]
This is likely just a problem with the nxm url association. As there have been changes to how we set that up since this was reported, I'm closing this issue as outdated.

If it's still an ongoing issue, please create a new issue with relevant information like version used and preferably a TraceLog you've gotten generated when trying to associate NMM with nxm urls.

Sorry for the inconvenience.
