### ISSUE TITLE
Cant renable mods after all become disabled

### ISSUE THREAD

**Issue by Wolfgang0302** [Nexus-Mods/Nexus-Mod-Manager#134]
When I opened NMM to check my fallout 4 mods something popped up about a plugin.exe cant only be read I think so I selected ok, then all my mods were randomly disabled and none of them could be renabled.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
