### ISSUE TITLE
Mods not working?

### ISSUE THREAD

**Issue by Userbotted** [Nexus-Mods/Nexus-Mod-Manager#137]
So I have some visual mods that are not working, and for the past few months I have been doing everything I can to try and get them to work, such as verifying game cache, verifying integrity of game files,  I disabled and enabled all my mods, etc. I still have not yet to find a solution for this problem.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
