### ISSUE TITLE
Can't download almost any mod

### ISSUE THREAD

**Issue by Youtubegamstertams** [Nexus-Mods/Nexus-Mod-Manager#150]
When I want to download any mod for Skyrim in NMM it will write : This mod can't be added or somethng like this... Does anyone know what to do with it? 0.o  BTW- Sorry for my english  ^.^

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
