### ISSUE TITLE
NMM does not install meshes/etc. if game is in Symlinked folder

### ISSUE THREAD

**Issue by BlueRaja** [Nexus-Mods/Nexus-Mod-Manager#157]
If the game folder in Steam is symlinked to another folder, installing mods through NMM _mostly_ works, except that textures/meshes/materials do not install correctly.

This is commonly done to move games to/from SDD to improve loading time/save space.  I personally use [Steam Mover](http://www.traynier.com/software/steammover) to automate this process.

See [here](https://forums.nexusmods.com/index.php?/topic/3554020-nmm-not-installing-texturesmeshesmaterialsinterface-files-in-data-folder-using-symlink/) for more details.  I'm playing Fallout 4, not sure if it's the same for other games.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
