### ISSUE TITLE
Skyrim.esm is Missing (Special Edition)

### ISSUE THREAD

**Issue by Halliphax** [Nexus-Mods/Nexus-Mod-Manager#160]
Not sure if I'm the only one that's had this.

The conditions to recreate:

1 - Install Skyrim on a secondary HDD (not C:\)
2 - *Move* the Skyrim folder into a parent folder on the same drive or rename the Skyrim folder
3 - Launch NMM

Expected Result: NMM cannot detect the install, rescans and works from there
Actual Result: NMM rescans for the install and finds it, but upon trying to launch NMM for Special Edition it will say "Skyrim.esm not found"

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
