### ISSUE TITLE
Installation of mods stops and doesnt continue

### ISSUE THREAD

**Issue by Luthur7** [Nexus-Mods/Nexus-Mod-Manager#161]
I had a queue of mods waiting to be installed one after the other, but instead NMM just hung there doing nothing. Waited 30 min and nothing.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
