### ISSUE TITLE
SKYRIM SE CRASH ON LAUNCH WITH NMM

### ISSUE THREAD

**Issue by Medzzzzz** [Nexus-Mods/Nexus-Mod-Manager#166]
Skyrim SE automatically closes. however when launching the game with the exe. or launcher itself, it works normally

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
