### ISSUE TITLE
constent scroling

### ISSUE THREAD

**Issue by yubelbloodfallen** [Nexus-Mods/Nexus-Mod-Manager#170]
i am having a problem with the manger in its self where it indefantly scroles down i happens on all of my games wich use the mod manger and it happen after i deactavated all of the mods on skyrim

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
