### ISSUE TITLE
Mod loads not showing

### ISSUE THREAD

**Issue by KrosTheProto** [Nexus-Mods/Nexus-Mod-Manager#171]
Hi, recently I move my NMM and Steam games to a new hard drive, problem is all my mods are loaded but all show to red circle with the line through it and I cannot enable, reenable them but they are loaded. Newly installed mods do show, This issue is on Skyrim, Fallout 4 and New Vegas. other games im not sure.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
