### ISSUE TITLE
NMM Doesn't Update Mods that have newer versions

### ISSUE THREAD

**Issue by 13lbaseball** [Nexus-Mods/Nexus-Mod-Manager#174]
I have the most up to date version of the NMM (0.63.14) and whenever I have the manager search for mod updates, it does not actually update the versions.  Is that inherent (am I'm plainly stupid) or am I missing a setting to make it so that it will also update the version of the mod whenever I search for mod updates?

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
