### ISSUE TITLE
Mods for witcher 3 \ fallout 4 

### ISSUE THREAD

**Issue by Sagethunder** [Nexus-Mods/Nexus-Mod-Manager#191]
the mods will not stay active the older ones i had stay active even if i disable them

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
