### ISSUE TITLE
Download Error and Many Virus Report on Nexus

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Nexus-Mod-Manager#192]
I have this Problem about 2 weeks. When I starting a download via NMM i get the message Server is busy of unaviable after that i get an download error. i testing it with direct download but the funny Thing is when i starting it get different Messages like thsi site is dangerous. if i have a downloadet file get a Virus Report from Windows Defender?????????????!!!!!!!!!!!!!!!!!!!! i dont understand it i Need help! i dont wont to reinstall the complet shit

**Comment by ghost** [comment]
PS: sry for my bad english

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
