### ISSUE TITLE
NMM locks up when a mod installer can't find an image

### ISSUE THREAD

**Issue by Corderoa** [Nexus-Mods/Nexus-Mod-Manager#193]
I've noticed that NMM will crash during mod installation if the image specified by the installer cannot be found. Rather than closing, the installer continues to function until I hit the "Next" button, at which point the next page fails to load and the installer freezes; at this point I can no longer close the installer popup, and can therefore not close NMM without going through the task manager.

It really feels like this should be captured and the invalid image skipped, rather than crashing the entire mod manager.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
