### ISSUE TITLE
Mods will activate, but won't appear in game

### ISSUE THREAD

**Issue by Caiden-Root** [Nexus-Mods/Nexus-Mod-Manager#201]
Title says it all. My mods download, install, then activate. I start Skyrim Special Edition (yes, the mods are SE mods, and they are downloaded for the SE) and none of the mods actually did anything in my game.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
