### ISSUE TITLE
all my mods turned off and they dont turn on

### ISSUE THREAD

**Issue by dogemod** [Nexus-Mods/Nexus-Mod-Manager#208]
i have around 90 mods for skyrim but all turned off all of the sudden they still work but ill have to reinstall them all they should add a group unistall and a group install

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
