### ISSUE TITLE
Nexus Mods webpage can't read my installed NMM

### ISSUE THREAD

**Issue by wasdariel** [Nexus-Mods/Nexus-Mod-Manager#211]
I think the new layout for the new layout for the page is the one to blame here because I have the latest version of the NMM installed currently in my computer. I really like the new layout, but i hope they tweak this issue rather soon

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
