### ISSUE TITLE
Starting Error

### ISSUE THREAD

**Issue by 1Blackomn01** [Nexus-Mods/Nexus-Mod-Manager#221]
Hello, I keep getting an Error when starting up Fallout New Vegas

Application load error 5:0000065434

I keep getting this when I try to Launch FONV from the NMM

Thanks
![img_1100 1](https://user-images.githubusercontent.com/35183167/34646211-f274b658-f316-11e7-9708-df4121ceaec3.JPG)

**Comment by Arefu** [comment]
https://steamcommunity.com/app/22380/discussions/0/617320628354255875/
https://answers.ea.com/t5/Battlefield-Bad-Company-2/APPLICATION-LOAD-ERROR-5-0000065434/td-p/6097125

Both things point to **Steam** not NMM

**Comment by ndotb** [comment]
I'm leaving this workaround here for posterity so that people don't drown in forum ilk:

If you have steam set to span multiple drives and FNV is installed on a different drive,
1. Create a symbolic link to the install drive by running `mklink /d "c:\Program Files (x86)\Steam\steamapps\common\Fallout New Vegas" "[game drive]:\[game root folder]\Steam\steamapps\common\Fallout New Vegas"`
2. In NMM, click the Settings icon (two gears)
3. Click the Fallout: New Vegas tab
4. Change the Fallout: New Vegas Directory to `c:\Program Files (x86)\Steam\steamapps\common\Fallout New Vegas`,
5. Click OK
6. Restart NMM and play normally.

I haven't traced the code to find the NMM bug (yes, it is an NMM bug) that doesn't support multiple drives under Steam, but it should recognize and support it since it has been a Steam feature for much longer than my memory serves.  Somewhere there's a "..\\..\\.." that needs to be replaced.
