### ISSUE TITLE
NMM can't handle mods with individual files larger than ~2GB

### ISSUE THREAD

**Issue by squid-box** [Nexus-Mods/Nexus-Mod-Manager#225]
With Fallout 4 VR being actively improved by the modding community, there have been some optimization mods that include large files (read: up to 11GB). The way NMM currently handles files makes it impossible to handle files larger than 2147483591 bytes, since it will read the entire file into a byte[]. [(C# arrays can have a maximum of 2147483591 elements)](https://stackoverflow.com/questions/3944320/maximum-length-of-byte/18347039#18347039).

Note: This is just a limit per unzipped file, you can have several 2GB files in the same mod archive and NMM seems to handle it fine.

The offense takes place Util/Archive: GetFileContents, but I don't know enough about how NMM's file management is desgined to actually change this.

**Comment by DuskDweller** [comment]
Hi @squid-box , if you want to help I can point you in the right direction:
- you should add a function handling the memory stream inside Util/Archive (eg. GetFileStream) that behaves a bit like GetFileContents but using a stream.
- then the intermediary method to be called inside Mod (Fomod, Omod, etc) should be something like .GetFileStream instead of .GetFile.
- you'll just need to call that inside NexusClient/ModManagement/ModFileInstaller: InstallFileFromMod and pass a stream instead of a byte[] to GenerateDataFile down below.

(all the other instances of GetFile calls are for small specific files like screenshots, so no need to change everything interacting with it)
