### ISSUE TITLE
Virtual Install problem

### ISSUE THREAD

**Issue by quochunganhphu1** [Nexus-Mods/Nexus-Mod-Manager#226]
this new feature of nexus mod manager caused some of my armor mods broken, i think the problem is it can't find its meshes, if i install the mod manually, it works just fine. Is anyone know how to disable the virtual install feature?

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
