### ISSUE TITLE
Stuck at install 100%

### ISSUE THREAD

**Issue by thejonincactuar** [Nexus-Mods/Nexus-Mod-Manager#227]
Multiple times today I have had an issue where occasionally I will download a mod and go to install it, and it will get to 100%, the tick will appear next to it, but it will stay as status "Running" with 100% progress. I obviously then can't install anything else as they are queued.

I then end up having to restart NMM through task manager, where I find the mod wasn't installed at all. Trying to install it again, or any other mod for that matter, produces the same issue. The only fix is for me to completely restart my PC.

It has definitely done it at least twice after using Add Mod from File, so it could possibly be linked to this.

My NMM is up-to-date.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
