### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by R3dSparks** [Nexus-Mods/Nexus-Mod-Manager#235]
I recently installed NNM again and noticed a visual bug. It's not causing problems with the functionality, but it's pretty annoying. A ghost image of the mod list appears and stays at the position where NMM opened and doesn't move if I move the window.

![nmmbug2](https://user-images.githubusercontent.com/22276152/35484416-d457b73e-044f-11e8-8e15-f42d95a12a1e.PNG)
 
Im using a AMD FX-8350 Processor, a AMD Radeon R9 270 GPU and Windows 7.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
