### ISSUE TITLE
Can't rearrange plugins using drag and drop..

### ISSUE THREAD

**Issue by vinodkumarreddy** [Nexus-Mods/Nexus-Mod-Manager#241]
I am not able to reposition any of my plugins in the plugins tab.Earlier(in previous builds) this used to happen if I try to move a plugin above any of it's master plugin.Now i am not able to move any mod in the plugin's tab.

**Comment by skaldond** [comment]
i got the same issue. cant even rearrange with the arrows they are grey'd out. it appeared in NMM 0.63.17

**Comment by squid-box** [comment]
It works fine for me with Fallout 4 in NMM0.64.0, both using arrows and dragging them around.

I think you need to provide some more info on what game you're modding, and what mods you've got that cause this.

**Comment by skaldond** [comment]
fallout 4 AND skyrim special edition. mods i cant move? ALL of them.
screenshots at the links below.
[https://www.dropbox.com/s/gm0iyxlrouvpgc7/skyrim.jpg?dl=0](url)
[https://www.dropbox.com/s/n9b55b6hjge88q6/fallout%204.jpg?dl=0](url)

**Comment by SerClegane** [comment]
Fallout 4 in NMM0.64.0 (amd I had this bug since NMM0.617) - I can't rearrange plugins. I found on Nexus that bug is connected with creation club files ( not esl  mods) maybe it's about their names (NMM can't see dashes there or something?) because I use method on Nexus and without CC files I can rearrange my plugins, as the link shows https://forums.nexusmods.com/index.php?/topic/6086198-skse64-and-esl-support-for-nexus-mod-manager/page-3

**Comment by nmirthes** [comment]
@squid-box  NMM is special-casing Creation Club esl/esm files using a hard-coded list in [https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/master/Fallout4/Fallout4GameModeDescriptor.cs](url) . It hasn't been updated in a while, plus SkyrimSE/FO4 now ship with a text file listing all CC plugins to date (Fallout4.ccc and Skyrim.ccc). Any plugins not on NMM's list get sorted oddly and are included in plugins.txt without asterisks. This seems to help break manually sorting the load order.

![nmm0640lo](https://user-images.githubusercontent.com/3878034/35948237-0812853c-0c42-11e8-9269-9f5b5ccfcc58.png)

![nmm0640pluginstxt](https://user-images.githubusercontent.com/3878034/35948656-ffe9d976-0c43-11e8-8c41-a2c8df2798e0.png)

**Comment by squid-box** [comment]
@SerClegane & @nmirthes : Thank you, that's what I needed to at least get started on this. I don't have a solution, but at least I know where the problem lies and when it started.

It's not a naming issue, and it's not related to whether or not the CC esl's are in the unmanaged list (the ordering is weird, yes. The missing asterisks are likely due to them not being enabled in NMM, at least I get asterisks when enabling them).

The problem lies in https://github.com/Nexus-Mods/Nexus-Mod-Manager/blob/master/GamebryoBase/PluginManagement/GamebryoPluginOrderValidator.cs - in ValidateOrder : After a change in October, it will always (as far as I can tell) fail the validation if an .esl is present in the plugin list.

@DuskDweller: I don't know enough about this to tell whether or not the entire "fix" is broken, or just needs some logic cleaned up, any idea on 4679e03f756d7c32d723c8c8d8e0b34051e12301 ? Removing the changes added there allows me to reorder plugins again.

Edit: I see that #177 mentions this exact thing.

**Comment by JimmyRJump** [comment]
Yep.  I'm in the same situation.  Unable to relocate any FO4 plug-in in NMM, using v0.63.19.  NMM also adds the .esl files to the totality of the amount of plug-ins as seen bottom right of NMM's interface, but esl plug-ins are not counted in NMM's plugins TAB.

I must however add that resorting plug-ins with LOOT (v12.3) works and the re-arrangement done by LOOT sticks and is visible in NMM.

**Comment by squid-box** [comment]
The plugin count was reported a while back in #178, but since it's just a visual issue I doubt anyone will bother with it :)

**Comment by JimmyRJump** [comment]
Well, NMM gives a warning when going over 255 plug-ins, which happens when having esl files added to the total.  On NMM's plugins tab there's 233 numbered plug-ins, but the total I now have on the Mods tab -including esl- is 256 and I get a red number and the excalamtion mark for having too many plug-ins.

The game does start, so, sure, it is but a visual issue, but an annoying and confusing one.

**Comment by CasperTheLich** [comment]
I've got this bug too. though, lucky for me i still remember how to adjust my loadorder manually in notepad. so no biggie, at least in my case.

**Comment by MrsLilEsarosa** [comment]
I've had this bug also. Sadly to unfortunate luck I had to re-download everything.  I found out the bug is a conflict with f4se (fallout 4 script extender). Without f4se I could rearrange plug-ins once I re-downloaded f4se I no longer could rearrange the plug-ins.

**Comment by UAVfan** [comment]
I've just run into the same problem. NMM was working perfectly, I then installed a mod through the CC ingame, NMM load order stopped working. Deleted said mod through CC ingame as I suspect this is what caused the problem but NMM still not able to edit the load order. Hope this helps.

**Comment by squid-box** [comment]
Grab [NMM 0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.9), and you should have no problems reordering your plugins, even with .esl's present.

**Comment by Dreifels** [comment]
> Grab [NMM 0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.9), and you should have no problems reordering your plugins, even with .esl's present.

V 0.65.10 - have same issue, arrow in plugins are grey, cannot move any
