### ISSUE TITLE
Failed to load files

### ISSUE THREAD

**Issue by makblueman** [Nexus-Mods/Nexus-Mod-Manager#250]
I had to remove a mod to reinstall it but now it's saying "data error has occurred, file is corrupted" but I know it's not because I had to just reinstall it wasn't a different file it was one I already had and that seemed to screw with others as well, how do I fix that, and every time I start NMM it says those mods failed to load and won't not show up, How do I fix that?

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
