### ISSUE TITLE
Mods dont work

### ISSUE THREAD

**Issue by Ghost153** [Nexus-Mods/Nexus-Mod-Manager#257]
Hello everyone i need help when i download mods for fallout 4 in NMM and enable it when i start the game and start playing the mods dont work pls help me

**Comment by DANKBOY69** [comment]
same

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
