### ISSUE TITLE
Skyrim.esm is disabled

### ISSUE THREAD

**Issue by AverageGamer14** [Nexus-Mods/Nexus-Mod-Manager#258]
Pretty much in the title, I can get into the game and play it that's not the issue. It's when I go to use mods and most of them depend on that file but for some reason which I can't figure out it says it is disabled which makes every other mod not work even tho it is checked.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
