### ISSUE TITLE
Mod updates not working

### ISSUE THREAD

**Issue by FenrirIII** [Nexus-Mods/Nexus-Mod-Manager#263]
The automated detection for mod updates is not working. It finds maybe one or two mods with updates but doesn't find any other despite most being updated.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
