### ISSUE TITLE
0.64.3 buged load order

### ISSUE THREAD

**Issue by DocDeath666** [Nexus-Mods/Nexus-Mod-Manager#265]
hi with 0.64.3 you can no longer change load order the arrows are greyed out

**Comment by Lucidi0us** [comment]
I haven't been able to change the load order for several versions.  Started using notepad++ and LOOT to manage that as a work-around.

This issue is likely the same as https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/241

**Comment by erjh** [comment]
The issue is still present in 0.65.1. It can be worked around using export / import load orders from the clipboard, Notepad, and/or LOOT, but it's still an inconvenience. 

[https://forums.nexusmods.com/index.php?/topic/6588751-security-update-for-nexus-mod-manager/page-5#entry59540366](url) is a post that describes a potential code work-around, though what problems it might cause I have no idea (IANAP).

**Comment by squid-box** [comment]
Grab [NMM 0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.9), and you should be able to change your load order again.
