### ISSUE TITLE
Download manager tab.

### ISSUE THREAD

**Issue by frazee13** [Nexus-Mods/Nexus-Mod-Manager#269]
every time i go back into another window it closes the tab entirely so ic an't tell which files/pages i need to navigate back to to fix missed files or whatever.
is auto-close something that is supposed to happen with that tab? it sucks

**Comment by frazee13** [comment]
man... idk why we had to go with a flash site also..
been a while since i played /modded skyrim
takes way longer this way with this site constantly trying to load the list of mods again when i'm looking at picture within a mods own page... that may eb seomthing else weird.

but having to load the proper results page after the first page (which you've gone through already) loads first after hitting back... feels like changes were made and nobody bothered to see if they felt..... uhhh..?
retarded or not... 
i think this would be the former, possibly a bug with waterfox... but fuck sites using flash that aren't and don't need to be animated or anything... waste of time

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
