### ISSUE TITLE
Support for RAR5 format

### ISSUE THREAD

**Issue by MrJamesFreeze** [Nexus-Mods/Nexus-Mod-Manager#278]
New version of WinRAR is using new **RAR5** format as default.

Thanks to that, some mods cannot be added to NMM.

Some users are not aware of this and that leave them confused. 
Especially mod authors who do not use NMM.

**Comment by squid-box** [comment]
NMM uses (afaik) 7z, which has had support for RAR5 (extraction) since 2015. 

The only reason I could think of where you'd encounter this problem is that running on a 32-bit system, NMM will only have 7za.dll which is only able to unzip ,7z files.

**Comment by MrJamesFreeze** [comment]
I have Windows 10 64-bit Education (like Pro) and every RAR5 file made by WinRAR (i have nothing else to create it) on my PC or downloaded from Nexus cannot be added. With RAR4, ZIP and 7Z no problem.

**Comment by MrJamesFreeze** [comment]
And I don't think that I am only one with this problem, because there was same problem with some mods from Nexus. Author then changed format (usually to ZIP) and problem was solved.

**Comment by squid-box** [comment]
Alright, so I've dug into this a bit. First of all: I've converted a small mod from 7z to a RAR5, and confirmed that the problem occurs (and Trace doesn't contain anything more than "Starting Add Mod Task").

The problem seems to lie in SevenZipSharp, as it doesn't identify the RAR5 file as a valid archive format. This doesn't seem too unreasonable as the last release of SevenZipSharp was in 2010...

I've put in a [request](https://github.com/tomap/SevenZipSharp/issues/13) to what seems to be the most active fork of it, if they manage to add it we could update the SevenZipSharp version used in NMM and it should work.

For anyone else looking into this, the check is in Nexus.Client.Util.Archive.IsArchive().

For testing: I've also attached [FakeMods.zip](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2018774/FakeMods.zip), which contains two fake mods RAR'ed in the respective formats.
