### ISSUE TITLE
Error registering this mod: Sim Settlements - Industrial Revolution - Sim Settlements - Industrial Revolution 3.2.1 Error: String was not recognized as a valid Boolean. 

### ISSUE THREAD

**Issue by merakles** [Nexus-Mods/Nexus-Mod-Manager#280]
Error registering this mod: Sim Settlements - Industrial Revolution - Sim Settlements - Industrial Revolution 3.2.1
Error: String was not recognized as a valid Boolean.

**Comment by merakles** [comment]
Error registering this mod: The Master Plan - MP_WR_Patch
Error: String was not recognized as a valid Boolean.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
