### ISSUE TITLE
NMM crashes on startup with tracelog message:Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by lol420** [Nexus-Mods/Nexus-Mod-Manager#305]
My NMM crashes on startup. I tried different versions of NMM from 6.4.3~6.5.4 and I receive the same message. I tried uninstalling and installing NMM again but the same tracelog messages pops up. 

Tracing an Unhandled Exception:
Exception: 
Message: 
	Object reference not set to an instance of an object.
Full Trace: 
	System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.MainForm.InitializeDocuments()
   at Nexus.Client.MainForm.ResetUI()
   at Nexus.Client.MainForm..ctor(MainFormVM p_vmlViewModel)

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
