### ISSUE TITLE
cant download Bodyslide "The action could not be completed because the file contains a virus or potentially unwanted software"

### ISSUE THREAD

**Issue by Olof0415** [Nexus-Mods/Nexus-Mod-Manager#341]
i have only been using NMM for a few days and it has worked fine but when i tried to download Bodyslide it said that there was a problem and on the TreceLog it said "The action could not be completed because the file contains a virus or potentially unwanted software" ish (translated it from Swedish) can anyone help?

**Comment by squid-box** [comment]
@Olof0415: Please upload the trace log (I'm fluent in Bork :))

**Comment by Olof0415** [comment]
its written in Swedish tho
[TraceLog20180524214035.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2036918/TraceLog20180524214035.txt)

**Comment by Olof0415** [comment]
Det gick inte att slutföra åtgärden eftersom filen innehåller ett virus eller potentiellt oönskad programvara. translates to The action could not be completed because the file contains a virus or potentially unwanted software.

**Comment by Olof0415** [comment]
ok well i have to go now but thx for the help

**Comment by squid-box** [comment]
So the reason is because the file is infeted with the trojan "Win32/Vigorf.A" - [mod author states it's a false positive](https://www.nexusmods.com/fallout4/mods/25?tab=posts), it's up to you to decide if you trust them or not.

The only thing we can do from the NMM side of things is to not crash when this occurs (but the file will still be blocked by Windows if it's infected).

**Comment by Olof0415** [comment]
thanks!!

**Comment by squid-box** [comment]
A fix for the crash was included in a release ~2 months ago, closing issue.
