### ISSUE TITLE
Doesn't always show which mods have updates.

### ISSUE THREAD

**Issue by BTGbullseye** [Nexus-Mods/Nexus-Mod-Manager#35]
There are some mods that are not the latest available on the site, but the manager says the numbers match. After downloading the updated mod, it still doesn't show the old version as being out of date. (tested with CBBE 2.2/2.3, and several other mods)

Not all mods appear this way.

EDIT: Sorry, forgot to mention this was for Fallout 4 side of things.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
