### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by TehLaztKing** [Nexus-Mods/Nexus-Mod-Manager#399]
The application does not let me download mods. I have removed the firewall guarding it however it still gives me a window to login on then says it encountered an unexpected problem. help!!!!

**Comment by Ghostwalker71** [comment]
Which version of NMM are you using?
What OS is installed on your computer?
Which site are you downloading from?

**Comment by phoensunfire** [comment]
I'm having the same issue
I'm using 0.63.14
I've been trying to get my mods from Nexus. 
![image](https://user-images.githubusercontent.com/40208753/41298565-7742a58c-6e16-11e8-9eca-1ec1068393a4.png)
![image](https://user-images.githubusercontent.com/40208753/41298586-8424da86-6e16-11e8-9e4a-3b316e7c3e1d.png)

**Comment by squid-box** [comment]
Check [this forum post](https://forums.nexusmods.com/index.php?/topic/6588751-security-update-for-nexus-mod-manager) - You have to update to 0.65.2 or above in order to login/download mods through NMM.

But if you're below 0.65.6 you will get an error about not finding updates - you can [grab 0.65.6 from GitHub](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.6).

**Comment by squid-box** [comment]
With no reply in a month I'm assuming the new version worked fine.
