### ISSUE TITLE
Mods not fully installing

### ISSUE THREAD

**Issue by thany** [Nexus-Mods/Nexus-Mod-Manager#4]
I've had a few mods that appear to have been installed from looking at the main screen, but are not at all installed, or only half-installed.

A few examples:
- [Achievements](http://www.nexusmods.com/fallout4/mods/12465) - Nothing is installed, so it appears the mod isn't doing anything at all.
- [LooksMenu](http://www.nexusmods.com/fallout4/mods/12631) - One file is installed, but a couple other files aren't. Again, this makes it look installed, but not actually functioning.
- [LooksMirror](http://www.nexusmods.com/fallout4/mods/13627) - The worst of these examples - the mod appears to do something, but shows bugs that a player will report as bleeding obvious. As if the mod hasn't been tested even for a darn microsecond. In reality, it's missing files that are required for it to work properly.

I'm sure I can come up with more examples if I set my mind to it, but it appears to boil down to this one-liner:
**It doesn't install anything other than a mod's "main file", if there's such a concept, and skips everything else.**

I'm using the latest version of everything. You name it, it's latest.

**Comment by ousnius** [comment]
All of these mods were created by the same author.
Maybe it has something to do with the compression format used?

**Comment by thany** [comment]
That would be coincidental at best, because those were _examples_, there are others with required files that aren't getting copied over.

**Comment by m-wulff** [comment]
I'm having the same issue.  I can browse to my FO4/Data directory, and see Textures, Meshes, etc folders, but they are all empty (except subfolders, which are then all empty, etc).  I was running mods fine through NMM for a couple months after the game came out, then I took a break around when the Automatron DLC came out.  I just tried starting to play again this week.

It might be worth noting that I completely reinstalled the game since I last played, and it's on a secondary HD (the old install and NMM were installed on my C:, the new install is on my E:, whereas NMM is still on C:).

**Comment by squid-box** [comment]
Far into the future, this seems to be working fine. The mods listed in the initial report add all files from the archive to the Fallout 4 folder.

Are any of you still experiencing this with the latest NMM?

**Comment by thany** [comment]
The few mods that I have installed or uninstalled, seemed to do so completely. But I can't say for sure.

**Comment by squid-box** [comment]
After this long, I'll just assume something was fixed... Closing the issue.

Thank you!
