### ISSUE TITLE
Nexus mod manager doesnt allow me to use my dlcs in skyrim

### ISSUE THREAD

**Issue by jotama123** [Nexus-Mods/Nexus-Mod-Manager#406]
Even thought i turn all the plugins for my mods to be on, when i start the game they automactly turn off, i cant play with the mods :C

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
