### ISSUE TITLE
NMM won't log in

### ISSUE THREAD

**Issue by AdventureHorse** [Nexus-Mods/Nexus-Mod-Manager#419]
So I recently installed NMM and tried to log in but it keeps giving me Login error: Wrong username or password. I copy-pasted the details I was entering into NMM onto the website and that logged me in just fine. Is anyone else having this problem/know how to fix it?

**Comment by dyslexicanaboko** [comment]
For argument's sake let's say the game we are targeting is Fallout New Vegas.

I debugged this problem and what I am seeing is that no matter what the parameters are that are provided to the REST call you get the error indicated above.

Example:
https://legacy-api.nexusmods.com/newvegas/Sessions/?Login&username={p_strUsername}&password={p_strPassword}

I tried this with my UN/PW and you get a 500 error from the server

Then I thought maybe it is because I use special characters, I URL encoded my UN and PW, it still didn't work.

Just food for thought. I can't fix this even if I wanted to, because it is on the service side.

Also - I strongly recommend not using WCF for REST, just use WebAPI, it's MUCH easier and far more supported for security and whatnot.

**Comment by inoch07** [comment]
Yeah, I've been downloading and uninstalling the various versions of the manager and, except on the site, it still it wont let me login. I am currently on version 0.65.6 and people on other forums have said that it fixed it for them. My OS is Win 10, I still have all the old mods from other games (hopefully that isn't an issue), and I know very little about computers much less coding. Idk, this all seems like a huge inevitable cluster what with government regulations from countries you don't belong to getting in between you and the best creepy anime mods. Also, I tinkered with my firewall and don't think that is the problem.

**Comment by Ghostwalker71** [comment]
If you have attempted and failed to pass the security password check multiple times, there is a chance that your account has been placed in a heightened security state. Try opening the website in your browser of choice and seeing if you can log in or if you will need to effect more than usual steps to log in. once you are able to log in with your browser, then try again with NMM

**Comment by inoch07** [comment]
For me that doesn't seem to be the problem.

**Comment by inoch07** [comment]
I've seen that a trace log should be attached. I'm just wondering if it should be put in a message like this one or submitted some other way. 

Latest version worked.

**Comment by squid-box** [comment]
@AdventureHorse: are you using your email to log in? Try using your username instead and see if that works.

**Comment by squid-box** [comment]
Note that NMM cannot authenticate you with an email address as your username, you need to use your Nexus username when logging in.

With [NMM 0.65.9](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.9), the login form will now enforce using a username (won't allow email). Hopefully that will resolve most login issues people are reporting.

Closing this issue.
