### ISSUE TITLE
my mods doesnt appear in game

### ISSUE THREAD

**Issue by bbcredds** [Nexus-Mods/Nexus-Mod-Manager#440]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
ok, so i bought a new pc, donwloaded skyrim, install NMM, everything normal, i strat downloading mods, the basic ones, SKYUI, cbbe, inmersive armors and weapons, any way like 30 of them, they are installed and activated in the correct way, they all appear in data files at the launcher, their esp file is activated, but when i start my game only a few of them appear in game, i mean some of them work perfectly well, as they should, but most of them is like they are not even installed, nothing. when i close the game and open NMM some of the mods that dindt work appear unactivated.

i have tried everithing.. from uninstall them to uninstall the NMM, to reinstall them, to instal them mannually and ith the NMM
 
PLEASEEEE HELPPPP MEEE

- NMM version:0.65.2

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
