### ISSUE TITLE
"Specified cast is not valid" Error

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Nexus-Mod-Manager#465]
I've been getting an issue that prevents me from using NMM with New Vegas. After doing a clean re-install of both NV and NMM, i opened NV once, just to make sure everything was set up properly, and then i installed NMM. Everything went fine, until it asked me to select the directories for the mods. After clicking OK it gives me this error:

[TraceLog20180706234545.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2172107/TraceLog20180706234545.txt)

Again, all of this was after a clean re-install of both NMM and NV, so no mods were present.
I restarted my PC, tried again, and got the same error, however the trace log is different:

[TraceLog20180707001706.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2172104/TraceLog20180707001706.txt)

**Environment**
- NMM version: 0.65.7
- Mod(s) used: None

**Comment by dyslexicanaboko** [comment]
@NotSucc which screen does this bomb out for you on? I am trying to reproduce the problem, but I am not able to. I will try a few more things, but I have a feeling I won't be able to make it fail. I am guessing, but this could have something to do with your registry settings since those weren't working too great until I fixed them recently.

**Update 1**
So just a wild guess, but it looks like this has something to do with it:
```
Checking: FalloutNV.CSharpScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.CSharpScript.dll: cannot find dependency CSharpScript, Version=1.1.6759.17536, Culture=neutral, PublicKeyToken=null
    Checking: FalloutNV.dll
        Initializing: Nexus.Client.Games.FalloutNV.FalloutNVGameModeFactory
    Checking: FalloutNV.XmlScript.dll
        Cannot load C:\Program Files\Nexus Mod Manager\GameModes\FalloutNV.XmlScript.dll: cannot find dependency XmlScript, Version=1.1.6759.17536, Culture=neutral, PublicKeyToken=null
```
This is in both of your trace logs.
You are missing the following DLLs in this location "C:\Program Files\Nexus Mod Manager\GameModes\":
1. FalloutNV.XmlScript.dll
2. FalloutNV.CSharpScript.dll

**Update 2**
I figured out the core problem, tested it out and solved it (pretty sure).
Nexus.Client.Games.Settings.SetupDirectoriesControlVM.LoadSettings() the following line was blowing up with good reason:
`(bool?)k.GetValue("MultiHDInstall", null)`
You can't cast a boolean string like so "False" to a nullable boolean. This _will_ cause an invalid cast exception.

**Comment by squid-box** [comment]
@NotSucc: There's a potential fix in the latest version ([0.65.8](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases/tag/0.65.8)), please try that.

**Comment by ghost** [comment]
It works now, thank you so much!

**Comment by squid-box** [comment]
Great :)

@dyslexicanaboko: Good work finding and fixing this!
