### ISSUE TITLE
Does not start with Unrecognized Game Mode

### ISSUE THREAD

**Issue by Fed13** [Nexus-Mods/Nexus-Mod-Manager#5]
That's very frustrating.

I uninstalled a game and now I cannot start mod manager.
It does not start because the game is no more. I can't change the game because I can't start the manager.

I tried looking for some ini in manager's installation folder and found none.
I tried looking for some ini in user\documents\nexus nod manager - found only tracelogs there.
I tried reinstallind the mod manager.

It sould be unnecessary to even do that. If a game mode cannot be recognized - take me to rescanning and choosing the game. Don't fuck everything up.

So my options for now look like a) uninstall the manager completely, loose the info for the third game, and install manager again, b) install the game back where it was in the past, start manager, choose new game, untistall the old game. Both of this options look crappy.

Unrecognized Game Mode

Nexus Mod Manager is not set up to work with The Witcher 3

If The Witcher 3 is installed, rescan for installed games from the Change Game toolbar item.

**Comment by ousnius** [comment]
The configuration files are in "%HOMEPATH%\Local\Black_Tree_Gaming". Otherwise I can't help you, I'm not involved in the development in any way.

**Comment by ghost** [comment]
I just now quickly tried to reproduce this with Morrowind. When NMM recognizes that a game is gone, it automatically sends you back to the window where you choose your startup game or where you can rescan your game library.

Maybe something different with The Witcher 3? Need to download the game to my laptop to test this.

EDIT:
I can't reproduce this error, as my **The Witcher 3** folder gets recreated when I delete the game.
Logs would probably help out here.

**Comment by Fed13** [comment]
I'm not sure if I can find the logs. But it probably does not matter now.
Maybe it's my system (win7), maybe it's the history of updates and reistalls...
Anyway, since NMM is almost history (http://www.nexusmods.com/fallout4/news/12905/?), there's not much sense in fixing it.

**Comment by dontrolle** [comment]
Hi. Long time ago, and the issue is closed... but hey - somebody might trip over this issue, when dealing with a refusal to startup because of *"Unrecognized game mode"* relating to an uninstalled game. (And hey - [Wisdom of the Ancients](https://xkcd.com/979/).)

I got the error; looked around in the config + here and there in the code (searching for "unrecognized" did the trick). Guessed that there might be a way to reset NMM to stop looking for an uninstalled game. It turned out that the easiest (for me) simply was to use the provided config-option to stop remembering the game mode (which pointed to an uninstalled game). 

In the config file (for me, under `%HOMEPATH%\AppData\Local\Black_Tree_Gaming\NexusClient.exe_Url_[...]\[NMM_version]`) find `user.config`. Find RememberGameMode and set it to False:

`
            <setting name="RememberGameMode" serializeAs="String">
                <value>False</value>
            </setting>
`

Start NMM. No error, and you now have to choose which game to manage.

**Comment by drasafasforis** [comment]
Hi, dontrolle pointed me in the right direction for the "Could not initialize Fallout: new vegas game mode "  error, but in my case the RememberGameMode line was already set to false. Instead of this there was some errors in the custom load method in my config file. I reverted my config to a previous version that worked in the past, and this solved my issue.
