### ISSUE TITLE
Cannot use mod manager after closing game

### ISSUE THREAD

**Issue by BrandonNoble** [Nexus-Mods/Nexus-Mod-Manager#527]
Upon closing/exiting a game (either using the menu system or forcibly a la alt+f4 or the processes panel) the mod manage cannot be interacted with as normal. The best way I can describe the issue is think of the desktop of the PC as a whole being layers of images like in Photoshop. The wallpaper is the base layer, the icons are the next layer, the taskbar is after that and the top most layer is a series of layers being open programs, such as the mod manager and a browser and a game. Anyways, after exiting the game the mod manager hides behind the taskbar layer and in front of the icons layer, and cannot be used. Cannot exit without using the task bar, cannot launch the game again or check any tabs.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
