### ISSUE TITLE
My mods either won't show up at all or are there but don't fully work. And direct mod download is bugged.

### ISSUE THREAD

**Issue by PhoenixtheKingofFire** [Nexus-Mods/Nexus-Mod-Manager#55]
I got some mods that grant new armors and new eye colors. I even got the cheat terminal thing and only a few would reveal themselves all while others act as if they don't exist. Not only that, but I can't directly download the mods from the site and have to manually download them. I don't know what exactly to do and I can't find anything to fix it.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
