### ISSUE TITLE
NMM encounters error on startup

### ISSUE THREAD

**Issue by casilas2231** [Nexus-Mods/Nexus-Mod-Manager#584]
As soon as I open NMM it crashes and says it creates a tracelog and has to close

- NMM version: 0.65.2.0

[TraceLog20180828120727.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2326466/TraceLog20180828120727.txt)

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
