### ISSUE TITLE
Skyrim says esm is missing when is it's ticked in nexus mods

### ISSUE THREAD

**Issue by JOZANWICK** [Nexus-Mods/Nexus-Mod-Manager#588]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
I have installed mods on my skyrim through nexus mods manager but it wont load ingame as its is stated that it is missing esm files.I checked nexus mod manager and its ticked.Not just the mods but the dlc aswell however both skyrim.esm and update.esm are ok.

**Environment**
- NMM version: 0.65.2
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
