### ISSUE TITLE
The Mod organizer has overwritten something that made the NMM won't be able to use the NMM direct download option

### ISSUE THREAD

**Issue by Nicholas418** [Nexus-Mods/Nexus-Mod-Manager#594]
Same as the title. After i install the mod organizer, the download link for the Nmm just doesnt works for it anymore. The issue is that the mod organizer cannot log into the site therefore i cant use the mod organizer too. I can still install mods manually but if anyone can fix the problem it will be the best.
Thanks for reading and wish you have a nice day.

**Comment by squid-box** [comment]
It's a little hard to decode what the actual problem is, but some things:

* Grab the latest release off GitHub [here](https://github.com/Nexus-Mods/Nexus-Mod-Manager/releases).
* Run NMM as administrator, go into Settings and check the NXM URL setting.

Is something still not working after these steps?

**Comment by Nicholas418** [comment]
thx, i forgot to mention it was the url problem
