### ISSUE TITLE
Crash on selecting SSE from the menu, "Message: Illegal characters in path"

### ISSUE THREAD

**Issue by Accrobar** [Nexus-Mods/Nexus-Mod-Manager#596]
**Describe the bug** 
NMM worked yesterday, but upon launching today it errors when I try to launch SSE from the main menu. The message is 'illegal characters in the path'. I'll attach the trace log, which has all the mods I use in it. I only have texture mods, and haven't installed anything or touched anything since it was working yesterday. I looked through the faq, and googled too. Last mention of this kind of error I could find was in 2016, and has obviously been patched since then. The error is probably some mistake on my side. Any insight or help would be nice!

**Environment**
- NMM version: 0.65.2.0
- Mod(s) used: In tracelog, but all visual or ui stuff, no game changing.

**To Reproduce**
Not sure. Happens every time I try to launch though, even after restarting and reinstalling.

**Additional information** 
Antivirus already ignores NMM and all it's paths, to the best of my knowledge/ability. Did that when I first installed the program.
[TraceLog20180904182019.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2351127/TraceLog20180904182019.txt)

**Comment by Accrobar** [comment]
Just an update, I installed 0.65.9.0 today to see if that would change anything, and it didn't. Still the same crash, here is a tracelog from the updated version of nmm.
[TraceLog20180905103557.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2353941/TraceLog20180905103557.txt)

**Comment by squid-box** [comment]
I've added some error management to where your problem happens, which adds logging.

Since I can't reproduce it, It'd be great if you could grab it from [here (log in as guest if prompted)](https://build.ahlgren.io/viewLog.html?buildId=297&buildTypeId=GitHub_Nmm_Build&tab=artifacts) and try it out. It will install over your current version.

If you do try it, please start it with forced trace log creation (start menu shortcut with "Trace Mode", or start NMM with `NexusClient.exe /Trace`, then attach the new log here (even if NMM doesn't crash, it will behave incorrectly (you'll probably be able to reorder the official plugins)) so I can see more info on what goes wrong).

**Comment by Accrobar** [comment]
Hey, I surprisingly managed to fix the problem on my own. I don't know for sure what the root cause was, but I do know what I did to fix it. Somehow, steam had forgotten/decided that I didn't have SSE installed anymore. I "reinstalled" it, which was really just steam discovering that I already had the entire game installed, and then it worked. When I selected SSE in NMM after that, no more crash. I don't know if this is enough information to find the problem, but I hope this helps. I appreciate the response and help too!

**Comment by squid-box** [comment]
That seems reasonable given my suspicions. Skyrim has a .ccc file which specifies all Creation Club mods available, that NMM reads. I'm guessing that file was somehow corrupt causing this problem. 

I'd guess Steam repaired your installation and fixed that file. Either way I'll add a fix to make sure NMM handles this case without crashing.

Thanks for replying!
