### ISSUE TITLE
NMM claims "Login error: Wrong username or password"

### ISSUE THREAD

**Issue by dartmann** [Nexus-Mods/Nexus-Mod-Manager#631]
**Describe the bug** 
NMM claims that I am not using valid credentials although they work on the website. When I click on the login button (left bottom corner) NMM claims my Token expired and I have to login for renewal.

**Environment**
- NMM version: 0.65.10
- Mod(s) used: I am not sure how this should be of any value and therefore omitted my long list (of course I will fetch this up if necessary)

**To Reproduce**
No idea. I am pretty sure this is a local problem of my client but I am not ware how to solve it. Are there any local temporary files I could delete, for example?

**Additional information** 
The problem occurred from one to the other day and without any software update.

**Comment by squid-box** [comment]
Some people have reported success by simply changing their password, it seems some part of the NexusMods authentication system NMM uses needs to be "refreshed" and the password change seems to trigger this.

**Comment by dartmann** [comment]
> Some people have reported success by simply changing their password, it seems some part of the NexusMods authentication system NMM uses needs to be "refreshed" and the password change seems to trigger this.

Hey @squid-box thanks for your reply. I'll give this a try and provide feedback.

**Comment by pantheranoir** [comment]
I have changed the password and this did not help me at all.  Also logged off website and logged on and still did not help with the mode manager log on issue.

**Comment by squid-box** [comment]
Hmm, and you're logging in using your email address (should be the case since you're using 0.65.10)...

That's the extent of my troubleshooting so far :(

**Comment by pantheranoir** [comment]
Yes I do the same as website but it keeps saying it's wrong through.


Sent via the Samsung Galaxy S9, an AT&T 4G LTE smartphone
-------- Original message --------From: Joel Ahlgren <notifications@github.com> Date: 10/1/18  1:29 AM  (GMT-05:00) To: Nexus-Mods/Nexus-Mod-Manager <Nexus-Mod-Manager@noreply.github.com> Cc: pantheranoir <pantheranoir5@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [Nexus-Mods/Nexus-Mod-Manager] NMM claims "Login error: Wrong
  username or password" (#631) 
Hmm, and you're logging in using your email address (should be the case since you're using 0.65.10)...
That's the extent of my troubleshooting so far :(

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Nexus-Mods/Nexus-Mod-Manager","title":"Nexus-Mods/Nexus-Mod-Manager","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Nexus-Mods/Nexus-Mod-Manager"}},"updates":{"snippets":[{"icon":"PERSON","message":"@squid-box in #631: Hmm, and you're logging in using your email address (should be the case since you're using 0.65.10)...\r\n\r\nThat's the extent of my troubleshooting so far :("}],"action":{"name":"View Issue","url":"https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/631#issuecomment-425793466"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/631#issuecomment-425793466",
"url": "https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/631#issuecomment-425793466",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Nexus-Mods/Nexus-Mod-Manager] NMM claims \"Login error: Wrong username or password\" (#631)",
"sections": [
{
"text": "",
"activityTitle": "**Joel Ahlgren**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@squid-box",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Nexus-Mods/Nexus-Mod-Manager\",\n\"issueId\": 631,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Nexus-Mods/Nexus-Mod-Manager\",\n\"issueId\": 631\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Nexus-Mods/Nexus-Mod-Manager/issues/631#issuecomment-425793466"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 386160825\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by MSGaBe86** [comment]
It happend to me today.IOt just refuses to let me log in.Sooo....fix ya soft pretty pls ? ...and i was in such a mood to restart playing Skyrim...guess i`m not...

**Comment by dartmann** [comment]
I've tried @squid-box suggestion and it worked for me.

**Comment by squid-box** [comment]
The problem is that we're pretty limited on info regarding authentication from the NMM side (with good reason, you don't want to expose too much info from authentication systems), so other than suggesting stuff like this we can't really "fix the software".

You'd have to get in touch with the Nexus team if you believe it's something on the authentication side, but they'll likely refer you to Vortex :)

**Comment by dartmann** [comment]
When NMM offers an official API than it should be well documented. 
Why not expose authentication details? It should be exactly the opposite, so developers can build secure and reliable software that interacts with the corresponding API and users can make sure that their data is handled securely. Moreover, this can prevent hacky approaches which came due to reversing undocumented APIs.
