### ISSUE TITLE
I can't install mods

### ISSUE THREAD

**Issue by IEnceladusI** [Nexus-Mods/Nexus-Mod-Manager#68]
When I press "Download With Manager" at the nexus' site a buffer will show but nothing will actually show up in nexus mod manager or mod organizer. I have tried to see if this occurs with other mods and it does and because of it I literally can not do anything. Please help and thank you for reading.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
