### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by ianne7d** [Nexus-Mods/Nexus-Mod-Manager#685]
[TraceLog20190115222550.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/2762519/TraceLog20190115222550.txt)

i have no clue whats going on, all im trying to do is deactivate everything, make a hard save with them all off, then turn them all back on and continue where i left off, but something is making a trance error and idk why

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
