### ISSUE TITLE
Pressing down twice in a row 

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [Nexus-Mods/Nexus-Mod-Manager#71]
If you press the down key twice in a row in quick succession, your selection will first move down to the next listed mod before moving over to the description box and cause you to start scrolling, instead of continuing down the list of mods.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
