### ISSUE TITLE
I can not download any mods with Nexus Mod Manager. There is always an error

### ISSUE THREAD

**Issue by ThePhoenixBoss70** [Nexus-Mods/Nexus-Mod-Manager#712]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
_A short description of what the problem is_

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by KevinkenX** [comment]
"Immersive Weapons - Immersive Weapons" couldn't be downloaded: "Error trying to get the file: https://files.nexus-cdn.com/110/27644/Immersive Weapons-27644-1-5.7z?md5=yY_uDt86bluSMgPUNrEUZQ&expires=1555649347&user_id=67417596&rip=180.244.20.105".

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
