### ISSUE TITLE
Mods are not installing completely

### ISSUE THREAD

**Issue by TheBlueFireFox** [Nexus-Mods/Nexus-Mod-Manager#72]
After reinstalling my fallout 4 installation and wanting to reinstall the mods, I noticed that the textures and meshes are not there. Something similar happened when I installed DEF_UI some files are transferred to the correct location, but most aren’t. I am no expert, but I think there might be an issue in the installations process. 
Now I hope the problem is just with my mashine, if so please advice me how to get it working again.
Anyway thank you very much for all your work 
TheBlueFireFox
(V. 0.63.14)
How it should be 
![manual_installation](https://cloud.githubusercontent.com/assets/8324294/25306301/89bd0e56-278a-11e7-800e-233c2ff42686.PNG)

How it is for me
![nmm_installation](https://cloud.githubusercontent.com/assets/8324294/25306302/89bd5546-278a-11e7-9d6e-2b72d8b9a2bf.PNG)

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
