### ISSUE TITLE
NMM 70 "Server Unreachable" errors

### ISSUE THREAD

**Issue by viper1s** [Nexus-Mods/Nexus-Mod-Manager#730]
Pull this
I just shut down NMM , logged out and then back in to Nexus and it worked

**Comment by squid-box** [comment]
Please [force a trace log to be created](https://github.com/Nexus-Mods/Nexus-Mod-Manager/wiki/Bug-reporting#trace-log) and attach it to this issue.

The fact that you could authorize NMM tells me that you're not blocked from communicating with the new Nexus API, but for some reason the download fails - hopefully the reason is logged in the trace.

**Comment by squid-box** [comment]
Alright, odd but we'll chalk it up to weirdness.

**Comment by viper1s** [comment]
The other problem is stranger.
I did not have an SKSE64 launcher on the NMM drop down. Just custom
I said , Ok , let me try that (I had never set up a "Custom Launcher" for any NMM supported game
It launched 3 instances of Skyrim SE
This is straight from the Trace Log
Launching Skyrim SE (Plain)...
    Command: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\SkyrimSE.exe
    Succeeded
Launching Skyrim SE (SKSE)...
    Command: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\skse64_loader.exe
    Succeeded
Launching Skyrim SE (Custom)...
    Succeeded
Running Threads (0)

**Comment by squid-box** [comment]
I created #732 for this, there's definitely something weird going on - I have a hunch on what it could be.
