### ISSUE TITLE
Can't install any mods

### ISSUE THREAD

**Issue by B3G1NNER** [Nexus-Mods/Nexus-Mod-Manager#74]
When I press "Download With Manager" at the nexus' site a buffer will show but nothing will actually show up in nexus mod manager or mod organizer. I have tried to see if this occurs with other mods and it does and because of it I literally can not do anything. HELP PLS
![image](https://cloud.githubusercontent.com/assets/27945741/25324905/1e346b50-28d1-11e7-9f23-3ff3f80e3183.png)

![image](https://cloud.githubusercontent.com/assets/27945741/25324916/2a896b94-28d1-11e7-9693-89b8cbfff2b4.png)

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
