### ISSUE TITLE
Breaking things when they work fine.

### ISSUE THREAD

**Issue by Echo-Beach** [Nexus-Mods/Nexus-Mod-Manager#773]
Had 0.65.11 installed all was fine.

Update 0.70 appears when I start NMM, press cancel. UPDATE goes ahead. Then Fallout 4 would not work, find here and there is 0.70.2 so download that and Fallout 4 works. At least for 20-30 minutes and then crash.

This all happened Monday/Tuesday. 

I have tried again today and same thing crash to desktop. I have looked for a Tracelog.txt file and this is where I realised something was completely messed up. (I did find a tracelog file but, the information contained was not from my system, I do not even own Skyrim)

I had Nexus Mod Manager installed at C:\Nexus Mod Manager which I run as Administrator because Fallout 4 was on a different drive. (D:\Fallout 4)

I have a new folder in C:\Program Files, can you guess the name? Correct, it is Nexus Mod Manager.

I had no issues at all, with 0.65.11 why was 0.70 "forced" update?

Attached is image of how things look, only 1 mod is enable Settlement Alerts, the rest I do not know because if I click to enable them Disabled Icon does not change.

![Nexus Mod Manager 07002](https://user-images.githubusercontent.com/50681271/57813042-c3642300-7766-11e9-874d-4b61f58b7a3c.PNG)

That's all I have.

**Comment by squid-box** [comment]
The only thing forced about the 0.70 update is that you won't be able to go online with NMM with earlier versions, due to Nexus Mods updating their API. You can always use the older versions offline.

I can promise you you're not getting anyone elses trace logs. I'm not entirely sure what your reported problem is, did your installed mods get listed as deactivated after the upgrade?

It sounds like you've had your NMM installed to a non-standard directory, in that case you've got to also point the updating installer to that same directory or it's going to install NMM to the default directory, which is in Program Files.

Did you also set NMM to use a non-standard directory to store mod information?

Without a way to reproduce your problems it's hard to troubleshoot them.

**Comment by Echo-Beach** [comment]
Hi Squid-Box,
Thank you for reply.
I forgot to say, this was under Windows 7 Pro 64bit OS. (Yes, all updates and .Net done as of 15th May 2019)
The 0.70 came through as an update when I opened 0.65.11 and as you guys have been managing NMM since Nexus went to Vortex, I thought OK.  I tried cancel button as I was not sure but, the update went through. (0.70 did not allow F4SE load, 0.70.2 did)
There were no options to change directory. I did use the create backup option but the only reference to a backup option leads to 0.70. ( I use Agent Ransack as search tool)
Yes, I did have Fallout 4 and Nexus Mod Manager in custom locations, the MOD store was in Nexus Mod Manager directory. (Nexus was on SSD (C drive) and Fallout 4 was on Hybrid HDD (D Drive).
I did spend Monday and Tuesday with part of Wednesday, doing my best to resolve the issue, before coming here and commenting.  
This might be a 1 off that has only happened to me.  
That is the experience I have had, it will take a few days to rebuild the game to where I had Fallout 4 before. (I have crossed fingers that the save files will work)
The Tracelog file I found, I deleted. ( I could recover the file, if I used Test Disk under Linux ) 
Good luck in the future with the project
