### ISSUE TITLE
Nexus Mods not recognizing mod downloads via NMM.

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/Nexus-Mod-Manager#811]
_Please give as much information as you can, replace/remove italicized text._

**Describe the bug** 
Nexus Mods saying I haven't downloaded a mod when clearly I have through NMM.

**Environment**
NMM 0.70.5
https://www.nexusmods.com/skyrimspecialedition/mods/26000
https://www.nexusmods.com/skyrimspecialedition/mods/26001

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
Download a mod via NMM from Nexus Mods.

**Additional information** 
On the mod pages above, it says, "You haven't downloaded this mod yet." when I clearly have since it shows in the appropriate category in NMM.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
