### ISSUE TITLE
Nexus mod manager

### ISSUE THREAD

**Issue by axoi92** [Nexus-Mods/Nexus-Mod-Manager#820]
hello, every time remove a mod from manager it don't remove it just removes it from the mod manager window but when I check fallout 4 data the files are still there and I have to remove them manually

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
