### ISSUE TITLE
Nexus sites not recognizing downloads via NMM

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/Nexus-Mod-Manager#833]
For whatever reason, the Nexus sites aren't recognizing downloads of mods via NMM.  The sites do say that I've downloaded the mods but the downloads counter isn't updating appropriately on the Nexus sites.  Please fix this.

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
