### ISSUE TITLE
NMM fails to launch any Game menus (.70.x)

### ISSUE THREAD

**Issue by Jnstnly** [Nexus-Mods/Nexus-Mod-Manager#837]
NMM Fails to launch any individual game's mod menus after upgrading from 65.2 (which ceases to do anything without defunct login tokens) and the tracelog doesn't seem to pull up the same issue as the regular culprit of NMM not launching - seemingly something to do with fonts not being supported?
Tracelog attached:
[TraceLog20190613174211.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3287205/TraceLog20190613174211.txt)

Any help would be appreciated for coming back to NMM for modding.

Thanks for your time.

**Comment by squid-box** [comment]
I'm s little confused as well, the log states that Calibri cannot be used in Bold...

I see you're running Win7, can you check in some word editor of you've got the font Calibri installed?

**Comment by Jnstnly** [comment]
Yep, straight into Microsoft Word and the default font is in fact Calibri - displayable as is, underlined, italic, and in bold.

Needless to say, NMM has been clean installed and uninstalled numerous times on both my C & D drives with the same error in every log.

**Comment by squid-box** [comment]
Googling around there seems to be some frequent-ish occurrence of this and similar errors (other fonts and styles) on Windows 7. Looking at the trace logs there's not really anything we can do on the NMM side - as soon as we try to load any UI this crash occurs.

My google findings indicated you try to re-install the font (I've attached my Win10 variants to this comment: [Calibri.zip](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3298894/Calibri.zip))

Otherwise it's mostly the standard "run disk check", etc.

It's weird that this would happen when moving from 0.65.2 to 0.70.x, as we haven't changed anything related to fonts.

**Comment by Jnstnly** [comment]
Uhhhh, yep! apparently windows just needed to reinstall the Calibri font suite for some reason, despite it functioning just fine as the default on pretty much all of my Word docs for years...

Regardless, everything seems to be working now, just waiting for the API to authenticate properly (I'm aware this is an intermittent server issue and don't suspect it to be tied to any further weird font-based shenanigans).

Thank you for your help, squid-box.
