### ISSUE TITLE
Im having problems activating certain mods

### ISSUE THREAD

**Issue by calathi** [Nexus-Mods/Nexus-Mod-Manager#84]
When I try activating mod's such as the mod configuration menu and Dimonized type3 female body it doesn't activate. I have looked in my activation queue and I get this error message when clicking on them.
![untitled](https://cloud.githubusercontent.com/assets/28547436/25827562/bb91b434-3443-11e7-955d-7e6e6e068cbb.png)
 I have looked around online and I cannot find a solution could someone help?

**Comment by DuskDweller** [comment]
It seems your antivirus messed up with NMM's dll files thinking it's malware, make sure that doesn't happen.

**Comment by calathi** [comment]
How would I stop this from happening exactly?

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported against a fairly old version, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
