### ISSUE TITLE
Added Enderal and messed up the rest

### ISSUE THREAD

**Issue by Moksha8088** [Nexus-Mods/Nexus-Mod-Manager#843]
Everything was working fine but I decided to have NMM 0.70.7 search for Enderal.  That worked fine and I was able to open Enderal Forgotten Stories, but I went to open Skyrim SE and got the dread Trace Log of Doom instead.

How can I fix this and would such a fix work for my other NMM managed games?

**Environment**
- NMM version: 0.70.7

**To Reproduce**
For me, it is reproducible by opening Skyrim SE.

**Additional information** 
Enclosed tracelog
[TraceLog20190616034303.txt](https://github.com/Nexus-Mods/Nexus-Mod-Manager/files/3294007/TraceLog20190616034303.txt)

**Comment by squid-box** [comment]
This is a threading issue, and like all threading issues it's weird. From the logs I can see that you first loaded Enderal and then switched to SkyrimSE. Almost immediately after the switch there's a crash due to a thread going missing, but then it continues to load a lot of SkyrimSE mods before the logs end.

It's this consistently happening for you? And it's it only if you switch from Enderal to SkyrimSE? Can you open SkyrimSE if it's the first one you open?

**Comment by Moksha8088** [comment]
Whatever caused the problem it self-corrected.  So, even if the sleeves seem too long with NMM, it will ride up with wear.  In the immortal words of Zora Fair-Child, "All better now".

**Comment by squid-box** [comment]
I guess all is well, for now. I'll close the issue, but please re-open this if it happens again.
