### ISSUE TITLE
Error while registering mod: Unofficial Conversion Error: Ungültige Versionsnummer

### ISSUE THREAD

**Issue by yarodinD** [Nexus-Mods/Nexus-Mod-Manager#889]
NMM 0.70.8,  Windows 10, Skyrim SE

I try to install "Bathing in Skyrim Special Edition - Unofficial Conversion" mod (https://www.nexusmods.com/skyrimspecialedition/mods/23730) and get the following error message:
Error registering this mod: Bathing in Skyrim Special Edition - Unofficial Conversion
Error: Ungültige Versionsnummer '1.43'. Zeile 1, Position 16. 

Of course maybe it's just a problem from the mod author, but it could also be an edge case in the version parser of NMM.

**Environment**
- NMM version: 0.70.8

**To Reproduce**
Try to download the mod mentioned above.

**Comment by squid-box** [comment]
This was a hard one to crack going from the NMM source :D

You're right in that it's a problem on the author's side, but maybe the error message from NMM could be more useful - so I'll do something about that.

The problem lies in the FOMOD info.xml file embedded in the mod rar:
![image](https://user-images.githubusercontent.com/864820/64888045-42f8f480-d66a-11e9-99f3-0239bc7b3575.png)

Note that the XML tag at the beginning of the file specified XML version `1.43` - this is not a valid XML version, and as such NMM can't parse this file. A safe bet would be putting `1.0` there instead.

**Comment by squid-box** [comment]
@yarodinD: So the "fix" is included in 0.70.9, but all it does is more clearly log the error as a problem with parsing the fomod's info.xml file - I also confirmed that changing the top line of that file to `<?xml version="1.0" encoding="UTF-16"?>` enables NMM to properly import the mod.

That will have to be fixed by the author of the mod (or you can manually do it).

I'm closing this issue now, please ping me if you don't agree :)

**Comment by yarodinD** [comment]
It works now. I informed the mod author about the issue. Thank you for the help.
