### ISSUE TITLE
can't move load order

### ISSUE THREAD

**Issue by mavmanzero** [Nexus-Mods/Nexus-Mod-Manager#894]
New today, I can't move any mods in my FO4 load order. This problem does not happen with SSE. I had this problem 6 or so months ago and forgot what I did exactly to fix it. I reinstalled as well. So far my work around is to close the program and manipulate the plugins.txt folder, them reopen the program... Old problem though, ever since Vortex was released. When I change my load order, the program locks up for several minutes.

**Environment**
- NMM version: _0.70.8_

**Comment by jbostrus** [comment]
I can think of a few things going on. Neither issue appears to be a bug in NMM, which I'll explain below. I see you listed 2 issues. Correct me if I misunderstand.

Issue 1) You can't manually change the load order inside NMM.
Issue 2) NMM locks up for some time when you change the load order through Vortex.

RE 1: This usually happens (that I've encountered) when somehow a master got placed after a plugin that required it, or if 2 files somehow were saying they both need each other as a master. If this ever happens to me (did once, was a broken mod from the author), I go through the whole order just checking which files require what masters and make sure they're not screwed up in the wrong order. If it did happen that it somehow got glitched up like that, I keep older load order lists to be imported for quick resetting to a previous state. Any files that aren't in that list then get auto sorted to the best guess location and that usually solves it for me. This isn't really an issue with NMM as you didn't use NMM to put them in the wrong place. I found the cause of this is usually another program improperly sorting the plugin files externally causing the issue with NMM. Things like LOOT (which Vortex uses). Early on I found this usually to be from things trying to sort .ESL files and doing so wrong. Then when NMM tries to deal with it, they're in the wrong place and NMM isn't sure how to deal with it so it just disallows ordering. If you have xEdit 4.x.x you could try to open it up with your load order set in the order that NMM doesn't like and try to open the whole order as it is. xEdit may give you insight into which mod is in the wrong place for tweaking your plugins.txt to quickly resolve it.

RE 2: It wasn't clear if the issue you have for this only happens in FO4 mode, or if that happens in SSE mode too. Also not clear if you're saying this happens when NMM is open and use Vortex at the same time, or if you were just stating the issue started happening around the time frame of when Vortex came out. Assuming the former, I'll explain what I believe is happening. If you have lots of plugin files, each time one is reordered the NMM code revalidates the entire load order to make sure you do not have a file where it shouldn't go. This is done to prevent a scenario such as Issue 1. So it takes a bit to rescan it all if you have many files. It sounds like you have NMM open while you use Vortex, and have Vortex do the sorting. This could cause NMM to queue up many rechecks to the order which would give the appearance of a lockup while it rechecks it all multiple times. How long it takes per check depends on your computer setup. This doesn't exactly sound like a bug as it seems to be doing what is intended, which is setting and validating the order as being read from the plugins.txt file. The solution to alleviate the issue would be to close NMM when using Vortex, then reopen NMM when you close Vortex. This facilitates it only doing the validation check once. If you don't want to do that, then likely you will just keep encountering the delay.

**Comment by JmsEllis** [comment]
I am experiencing Issue 2 when I attempt to modify the load order in NMM. I do not use Vortex. I have 383 total plugins (219 are enabled) in my load order for FO4. Any time I need to move item(s) in the load order the program stops responding. Sometimes for upwards of 5 minutes. This seems to happen any time the program has to make a modification to the load order including Installing or Uninstalling mods. I have taken to just manually modifying the plugins.txt file whenever I need to make a change. This issue seems to only start showing up when there are a large number of plugins in the load order. Until you approach 100 plugins it's not noticeable but after that it seems to get worse fast. At 383 plugins it would be debilitating if I couldn't edit them manually in the txt file.

**Comment by jbostrus** [comment]
This may have been resolved with 0.70.10 please test and advise.

**Comment by JmsEllis** [comment]
0.70.10 did appear to dramatically improve this issue. It's not super fast but it's responsive enough that I would feel comfortable calling the issue resolved.

**Comment by JmsEllis** [comment]
After upgrading again to 0.70.11 this issue appears to be completely gone :) load order changes are zippy fast again! Thanks so much for all the work you do <3
