### ISSUE TITLE
Mods will not install!

### ISSUE THREAD

**Issue by hrgirl1701** [Nexus-Mods/Nexus-Mod-Manager#90]
So apparently this is happening with a lot of different mods on normal Skyrim. Example would be Skyrim Community Uncapper! I can install Skytweak which gives a .esp but if I install any other mod that's a texture or anything else, it does not install!!! It seriously doesn't do anything with the file. Next time I load Nexus, it has that no smoking sign, as if I had installed it but it can't sense the files. HELP.

**Comment by DuskDweller** [comment]
Where is your game located? Where's the NMM VirtuaInstall folder located?

**Comment by wolfeng-db** [comment]
Are the files in .rar format? 

I had the same issue just now with some RAR files from the dragon age nexus.

**Comment by adkins2010** [comment]
@hrgirl1701 ,
NMM will often replace files such as textures and non-script files with symlinks.  The main files such as your .esp or .esm files will not be replaced with symlinks, but it will replace images, bump maps, sounds, etc. with symlinks to your NMM mod directory. 

This is a great way to save disk space and make it easy to enable and disable mods; the alternative approach to mod management would be to find particular files from one mod, delete that, and install from another mod installation directory.  The mod management can be very messy, and creates duplicate files on your hard disk.  

On the other hand, symlinks can be a bitch to fix.  I have had situations where symlinks for certain mods would break after some time.  A Saber Fate/Stay Night mod worked fine for some days.  Later, the mod broke completely.  I didn't know until some digging that I had these symlinks which, upon further investigation, turned out to be broken.  

Anything where mods might overlap are at risk.  And, I have noticed that new files aren't even being installed in some cases.  I now just copy and paste things into that my data directory.

**Comment by squid-box** [comment]
No response from OP for a year, closing issue.
