### ISSUE TITLE
在多字节的目标代码页中，没有此 Unicode 字符可以映射到的字符。

### ISSUE THREAD

**Issue by 91laodage** [Nexus-Mods/Nexus-Mod-Manager#904]
跟踪未处理的异常:
Exception: 
Message: 
	在多字节的目标代码页中，没有此 Unicode 字符可以映射到的字符。 (异常来自 HRESULT:0x80070459)
Full Trace: 
	System.ArgumentOutOfRangeException: 在多字节的目标代码页中，没有此 Unicode 字符可以映射到的字符。 (异常来自 HRESULT:0x80070459)
   在 System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Object structure, Boolean allowValueClasses)
   在 System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
   在 System.Windows.Forms.UnsafeNativeMethods.PtrToStructure(IntPtr lparam, Type cls)
   在 BrightIdeasSoftware.ObjectListView.HandleReflectNotify(Message& m)
   在 BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
