### ISSUE TITLE
nexus mod manger

### ISSUE THREAD

**Issue by axoi92** [Nexus-Mods/Nexus-Mod-Manager#934]
hello, my nexus mod manger is stuck on loading and won't start I re installed it many times and deleted map in &appdata%  dunno what to do

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
