### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by OldGamerDarthy** [Nexus-Mods/Nexus-Mod-Manager#936]
On 2 or 3 times random the nmm run good but if i install various mods i need close and reopen for the correct work and install the mods :( 

**Environment**
- NMM version: _0.1.0_
- Mod(s) used: _<link to mod(s) on Nexus>_

_Please remember to attach any trace logs you get in connection to this problem. Without these it will often be very hard to track down the bug._

**To Reproduce**
 _How to reproduce the problem_

**Additional information** 
_Anything that could help track down this problem, other software used, screenshots, etc._

**Comment by squid-box** [comment]
As part of cleaning up and getting a sense of current problems in NMM:CE, we're going through old reported issues. 

This issue is reported with minimal information, and isn't easily reproducible - so I'm going to close it now.

If it's still an ongoing issue, please create a new issue with relevant information like version used, mod(s) related to the issue, and any TraceLog you've gotten generated.

Sorry for the inconvenience.
